.PHONY: clean All

All:
	@echo "----------Building project:[ ZombieArena - Debug ]----------"
	@cd "ZombieArena" && "$(MAKE)" -f  "ZombieArena.mk"
clean:
	@echo "----------Cleaning project:[ ZombieArena - Debug ]----------"
	@cd "ZombieArena" && "$(MAKE)" -f  "ZombieArena.mk" clean
